AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 150

Metrics/AbcSize:
  Max: 100

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/MethodLength:
  CountComments: true  # count full line comments?
  Max: 50

Metrics/PerceivedComplexity:
  Max: 20

Naming/VariableName:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
